// Generated by gencpp from file button_box/ButtonInfo.msg
// DO NOT EDIT!


#ifndef BUTTON_BOX_MESSAGE_BUTTONINFO_H
#define BUTTON_BOX_MESSAGE_BUTTONINFO_H

#include <ros/service_traits.h>


#include <button_box/ButtonInfoRequest.h>
#include <button_box/ButtonInfoResponse.h>


namespace button_box
{

struct ButtonInfo
{

typedef ButtonInfoRequest Request;
typedef ButtonInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ButtonInfo
} // namespace button_box


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::button_box::ButtonInfo > {
  static const char* value()
  {
    return "fce55d8d6e1bc1923599409813fddc68";
  }

  static const char* value(const ::button_box::ButtonInfo&) { return value(); }
};

template<>
struct DataType< ::button_box::ButtonInfo > {
  static const char* value()
  {
    return "button_box/ButtonInfo";
  }

  static const char* value(const ::button_box::ButtonInfo&) { return value(); }
};


// service_traits::MD5Sum< ::button_box::ButtonInfoRequest> should match 
// service_traits::MD5Sum< ::button_box::ButtonInfo > 
template<>
struct MD5Sum< ::button_box::ButtonInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::button_box::ButtonInfo >::value();
  }
  static const char* value(const ::button_box::ButtonInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::button_box::ButtonInfoRequest> should match 
// service_traits::DataType< ::button_box::ButtonInfo > 
template<>
struct DataType< ::button_box::ButtonInfoRequest>
{
  static const char* value()
  {
    return DataType< ::button_box::ButtonInfo >::value();
  }
  static const char* value(const ::button_box::ButtonInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::button_box::ButtonInfoResponse> should match 
// service_traits::MD5Sum< ::button_box::ButtonInfo > 
template<>
struct MD5Sum< ::button_box::ButtonInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::button_box::ButtonInfo >::value();
  }
  static const char* value(const ::button_box::ButtonInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::button_box::ButtonInfoResponse> should match 
// service_traits::DataType< ::button_box::ButtonInfo > 
template<>
struct DataType< ::button_box::ButtonInfoResponse>
{
  static const char* value()
  {
    return DataType< ::button_box::ButtonInfo >::value();
  }
  static const char* value(const ::button_box::ButtonInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BUTTON_BOX_MESSAGE_BUTTONINFO_H
