# adjust pose to .action file

# goal definition

string geometry
string axis
string amount
---

# result definition
bool is_done
---

# feedback definition
# 0: unpressed
# 1: pressed
int32 process

